---
  server:
    port: 8081
  spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 50MB
    data:
      redis:
        host: localhost
        port: 6379
  aws:
    accessKeyId: ${AWS_ACCESS_KEY_ID}
    secretKey: ${AWS_SECRET_KEY}
    region: ru-central1
    s3:
      bucket: my-date-app
      endpoint: https://storage.yandexcloud.net

